name: devops app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
   
    - name: List Files
      run: |
       echo "Terry is teaching"

    - name: Install Dependencies
      run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt
       python -m pip install flake8

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out branch
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}

      - name: Build and Push Image
        run: |
          docker build -t ${{ secrets.USERNAME }}/devops:${{ github.sha }} .
          docker push ${{ secrets.USERNAME }}/devops:${{ github.sha }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'dv-cute-perch'
          publish-profile: ${{ secrets.AZUREPUBLISH }}
          images: ${{ secrets.USERNAME }}/devops:${{ github.sha }} .
         
      

      

    
    
  
    